version: '3.8'

services:
  # PHP-FPM сервис
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: loans_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - loans-network
    depends_on:
      - db

  # Nginx сервис
  webserver:
    image: nginx:alpine
    container_name: loans_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - loans-network
    depends_on:
      - app

  # PostgreSQL сервис
  db:
    image: postgres:15-alpine
    container_name: loans_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - loans-network

volumes:
  postgres_data:

networks:
  loans-network:
    driver: bridge